const bodyParser = require('body-parser')
const app = require('../server/index.js')

const contactRoute = require('./routes/contacts.js')
const newsRoute = require('./routes/news.js')
const searchRoute = require('./routes/search.js')
//categories
const boltsRoute = require('./routes/category/bolts.js')
const screwsRoute = require('./routes/category/screws.js')
const waresRoute = require('./routes/category/wares.js')
const nutsRoute = require('./routes/category/nuts.js')
const anchorsRoute = require('./routes/category/anchors.js')
const elementsRoute = require('./routes/category/elements.js')
const washersRoute = require('./routes/category/washers.js')
const otherBoltsRoute = require('./routes/category/other_bolts.js')
const otherWaresRoute = require('./routes/category/other_wares.js')
const itemRoute = require('./routes/category/item.js')
const filterItemsRoute = require('./routes/category/filterItems.js')
const filtersRoute = require('./routes/category/filters.js')
const loginRoute = require('./routes/auth/login.js')
const profileInfoRoute = require('./routes/profile/info.js')
const profileOrdersRoute = require('./routes/profile/orders.js')
const profilePaymentsRoute = require('./routes/profile/payments.js')
const profileShipmentsRoute = require('./routes/profile/shipments.js')
const pdfRoute = require('./routes/pdf.js')
const paymentRoute = require('./routes/payment/card.js')
const minPriceOrder = require('./routes/cart/minPriceOrder.js')
const addOrder = require('./routes/cart/addOrder.js')

app.use(bodyParser.json())
app.use('/api/contacts', contactRoute)
app.use('/api/news', newsRoute)
app.use('/api/search', searchRoute)
app.use('/api/category/bolts', boltsRoute)
app.use('/api/category/screws', screwsRoute)
app.use('/api/category/wares', waresRoute)
app.use('/api/category/nuts', nutsRoute)
app.use('/api/category/anchors', anchorsRoute)
app.use('/api/category/elements', elementsRoute)
app.use('/api/category/washers', washersRoute)
app.use('/api/category/other_bolts', otherBoltsRoute)
app.use('/api/category/other_wares', otherWaresRoute)
app.use('/api/category/item', itemRoute)
app.use('/api/category/filterItems', filterItemsRoute)
app.use('/api/category/filters', filtersRoute)
app.use('/api/auth/login', loginRoute)
app.use('/api/profile/info', profileInfoRoute)
app.use('/api/profile/orders', profileOrdersRoute)
app.use('/api/profile/payments', profilePaymentsRoute)
app.use('/api/profile/shipments', profileShipmentsRoute)
app.use('/api/pdf', pdfRoute)
app.use('/api/cart/min-price-order', minPriceOrder)
app.use('/api/cart/add-order', addOrder)

app.use('/api/payment/card', paymentRoute)

module.exports = app
